[package]
name = "base-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.32.5", features = ["cluster", "script", "tokio-comp"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.15"
vaultrs = "0.7.4"
