# version: "3.9"
# 
services:
  rabbitmq:
    image: docker.io/library/rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /opt/rabbitmq/data:/var/lib/rabbitmq

  valkey:
    image: docker.io/valkey/valkey:latest
    command:
      - "valkey-server"
      - "--save" 
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
      - "--dir"
      - "/data"
      - "--dbfilename"
      - "dump.rdb"
    ports:
      - "6379:6379"
    volumes:
      - /opt/valkey/data:/data

  etcd:
    image: quay.io/coreos/etcd:v3.6.4
    command:
      - etcd
      - --data-dir=/var/lib/etcd
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"
    volumes:
      - /opt/etcd/data:/var/lib/etcd

  openbao:
    image: docker.io/openbao/openbao:latest
    command: ["server", "-config=/etc/openbao/openbao.hcl"]
    ports:
      - "8200:8200"
    volumes:
      - /opt/openbao/data:/openbao/data
      - /opt/openbao/config:/etc/openbao
    cap_add:
      - IPC_LOCK
