[package]
name = "dyno-worker-linux"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
ssh2 = "0.9.5"
tokio = { version = "1.47.1", features = ["full"] }
vaultrs = "0.7.4"
