---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /opt/rabbitmq/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: valkey
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /opt/valkey/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /opt/etcd/data
---
apiVersion: v1  
kind: PersistentVolume
metadata:
  name: openbao-data
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /opt/openbao/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-config
spec:
  capacity:
    storage: 10Gi
  accessModes: [ "ReadWriteOnce" ]
  hostPath:
    path: /opt/openbao/config
