---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  type: LoadBalancer
  selector:
    app: valkey
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: LoadBalancer
  selector:
    app: etcd
  ports:
  - port: 2379
    targetPort: 2379
    name: client
---
apiVersion: v1
kind: Service
metadata:
  name: openbao
spec:
  type: LoadBalancer
  selector:
    app: openbao
  ports:
  - port: 8200
    targetPort: 8200
    name: http
