[package]
name = "mock"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
lapin = "3.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = "0.1.17"
